In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd drive/MyDrive/Capstone_Thesis/

/content/drive/MyDrive/Capstone_Thesis

In [3]:
!pip install -r requirements.txt

Requirement already satisfied: torch>=2.2 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 2)) (2.11.0+cu130)
Requirement already satisfied: transformers>=4.51 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 3)) (5.17.0)
Requirement already satisfied: datasets>=3.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 4)) (4.8.5)
Requirement already satisfied: accelerate>=0.30 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 5)) (1.15.0)
Collecting bitsandbytes>=0.43 (from -r requirements.txt (line 6))
  Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 9)) (2.1.3)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 10)) (2.2.3)
Requirement already satisfied: scipy>=1.11 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 11)) (1.16.3)
Requirement already satisfied: tqdm>=4.66 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 12)) (4.67.3)
Requirement already satisfied: matplotlib>=3.8 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 15)) (3.10.0)
Requirement already satisfied: scikit-learn>=1.4 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 16)) (1.6.1)
Requirement already satisfied: umap-learn>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 17)) (0.5.12)
Requirement already satisfied: openai>=1.30 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 20)) (2.54.0)
Requirement already satisfied: tiktoken>=0.7 in /usr/local/lib/python3.13/dist-packages (from -r requirements.txt (line 21)) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (3.32.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (2025.12.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (13.0.2)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (13.0.3)
Requirement already satisfied: nvidia-cudnn-cu13==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: nvidia-nccl-cu13==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch>=2.2->-r requirements.txt (line 2)) (3.6.0)
Requirement already satisfied: nvidia-cublas==13.1.0.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (13.1.0.3)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch>=2.2->-r requirements.txt (line 2)) (13.0.85)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.51->-r requirements.txt (line 3)) (1.31.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.51->-r requirements.txt (line 3)) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.51->-r requirements.txt (line 3)) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.51->-r requirements.txt (line 3)) (2025.11.3)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.51->-r requirements.txt (line 3)) (0.23.2)
Requirement already satisfied: typer in /usr/local/lib/python3.13/dist-packages (from transformers>=4.51->-r requirements.txt (line 3)) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.13/dist-packages (from transformers>=4.51->-r requirements.txt (line 3)) (0.8.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=3.0->-r requirements.txt (line 4)) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=3.0->-r requirements.txt (line 4)) (0.4.1)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.13/dist-packages (from datasets>=3.0->-r requirements.txt (line 4)) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.13/dist-packages (from datasets>=3.0->-r requirements.txt (line 4)) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.13/dist-packages (from datasets>=3.0->-r requirements.txt (line 4)) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.13/dist-packages (from datasets>=3.0->-r requirements.txt (line 4)) (0.70.19)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from accelerate>=0.30->-r requirements.txt (line 5)) (5.9.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0->-r requirements.txt (line 10)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0->-r requirements.txt (line 10)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas>=2.0->-r requirements.txt (line 10)) (2026.4)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->-r requirements.txt (line 15)) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->-r requirements.txt (line 15)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->-r requirements.txt (line 15)) (4.65.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->-r requirements.txt (line 15)) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->-r requirements.txt (line 15)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.8->-r requirements.txt (line 15)) (3.3.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.4->-r requirements.txt (line 16)) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.4->-r requirements.txt (line 16)) (3.7.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.13/dist-packages (from umap-learn>=0.5.6->-r requirements.txt (line 17)) (0.61.2)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.13/dist-packages (from umap-learn>=0.5.6->-r requirements.txt (line 17)) (0.6.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from openai>=1.30->-r requirements.txt (line 20)) (4.15.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from openai>=1.30->-r requirements.txt (line 20)) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /usr/local/lib/python3.13/dist-packages (from openai>=1.30->-r requirements.txt (line 20)) (0.17.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from openai>=1.30->-r requirements.txt (line 20)) (2.13.5)
Requirement already satisfied: sniffio in /usr/local/lib/python3.13/dist-packages (from openai>=1.30->-r requirements.txt (line 20)) (1.3.1)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio<5,>=3.5.0->openai>=1.30->-r requirements.txt (line 20)) (3.19)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<14,>=13.0.3->torch>=2.2->-r requirements.txt (line 2)) (1.8.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.13/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0->-r requirements.txt (line 4)) (3.14.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=3.0->-r requirements.txt (line 4)) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.13/dist-packages (from httpx<1.0.0->datasets>=3.0->-r requirements.txt (line 4)) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.13/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=3.0->-r requirements.txt (line 4)) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.51->-r requirements.txt (line 3)) (8.5.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /usr/local/lib/python3.13/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.51->-r requirements.txt (line 3)) (1.6.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.2.0->scikit-learn>=1.4->-r requirements.txt (line 16)) (3.1.2)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba>=0.51.2->umap-learn>=0.5.6->-r requirements.txt (line 17)) (0.44.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=1.9.0->openai>=1.30->-r requirements.txt (line 20)) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=1.9.0->openai>=1.30->-r requirements.txt (line 20)) (2.46.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=1.9.0->openai>=1.30->-r requirements.txt (line 20)) (0.4.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0->-r requirements.txt (line 10)) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets>=3.0->-r requirements.txt (line 4)) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.2->datasets>=3.0->-r requirements.txt (line 4)) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch>=2.2->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch>=2.2->-r requirements.txt (line 2)) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers>=4.51->-r requirements.txt (line 3)) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.13/dist-packages (from typer->transformers>=4.51->-r requirements.txt (line 3)) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from typer->transformers>=4.51->-r requirements.txt (line 3)) (0.0.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0->-r requirements.txt (line 4)) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0->-r requirements.txt (line 4)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0->-r requirements.txt (line 4)) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0->-r requirements.txt (line 4)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0->-r requirements.txt (line 4)) (6.8.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0->-r requirements.txt (line 4)) (0.5.4)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.13/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets>=3.0->-r requirements.txt (line 4)) (1.25.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers>=4.51->-r requirements.txt (line 3)) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich>=13.8.0->typer->transformers>=4.51->-r requirements.txt (line 3)) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.51->-r requirements.txt (line 3)) (0.1.2)
Downloading bitsandbytes-0.50.2-py3-none-manylinux_2_24_x86_64.whl (43.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 MB 35.1 MB/s eta 0:00:00
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.50.2

In [4]:
!python validate_capstone.py

All model-free capstone validation checks passed.

In [4]:
import torch

print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "None")

CUDA available: True
GPU: Tesla T4

In [12]:
!python capstone_robustness.py \
  --task squad \
  --backend hf \
  --model Qwen/Qwen3-4B \
  --n_samples 20 \
  --sample_offset 200 \
  --seed 42 \
  --typo_types keyboard deletion transposition \
  --match_typo_targets \
  --locations any \
  --severities 1 2 3 \
  --typo_difficulty hard \
  --keyword_strategy idf \
  --output results/qwen_squad_pilot.csv

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Design: 9 corrupted conditions + 1 matched clean condition(s); 200 total generations.
Loading weights: 100% 398/398 [00:29<00:00, 13.63it/s]
Running clean baseline | mitigation=none on 20 squad examples...
100% 20/20 [00:23<00:00,  1.19s/it]
Running keyboard | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1

=== PRIMARY SUMMARY ===
        model  task  severity typo_difficulty mitigation  n  requested_n  excluded_examples_due_to_errors  clean_score    score  absolute_drop  drop_ci_2.5  drop_ci_97.5  bootstrap_probability_drop_le_zero
Qwen/Qwen3-4B squad         1            hard       none 20           20                                0     0.949286 0.928571       0.020714    -0.074530      0.101429                              0.2912
Qwen/Qwen3-4B squad         2            hard       none 20           20                                0     0.949286 0.865281       0.084004    -0.047905      0.224488                              0.1070
Qwen/Qwen3-4B squad         3            hard       none 20           20                                0     0.949286 0.767662       0.181623     0.039048      0.343247                              0.0046

The full condition-level summary was written to disk; use it for secondary typo-type/location analyses.

Raw results: results/qwen_squad_pilot.csv
Summary:     results/qwen_squad_pilot_summary.csv
Primary:     results/qwen_squad_pilot_primary_summary.csv
Metadata:    results/qwen_squad_pilot_metadata.json

In [13]:
import pandas as pd

summary = pd.read_csv("results/qwen_squad_pilot_summary.csv")

summary[
    [
        "typo_type",
        "location",
        "severity",
        "error_rate",
        "mean_actual_severity",
        "severity_completion_rate",
        "mean_actual_char_operations",
    ]
].to_string(index=False)

'    typo_type location  severity  error_rate  mean_actual_severity  severity_completion_rate  mean_actual_char_operations\n     deletion      any         1         0.0                  1.00                      1.00                          2.0\n     deletion      any         2         0.0                  2.00                      1.00                          4.0\n     deletion      any         3         0.0                  2.95                      0.95                          5.9\n     keyboard      any         1         0.0                  1.00                      1.00                          2.0\n     keyboard      any         2         0.0                  2.00                      1.00                          4.0\n     keyboard      any         3         0.0                  2.95                      0.95                          5.9\ntransposition      any         1         0.0                  1.00                      1.00                          2.0\ntransposition      any         2         0.0                  2.00                      1.00                          4.0\ntransposition      any         3         0.0                  2.95                      0.95                          5.9'

# RUN 1: POSITION-SPECIFIC ROBUSTNESS
# Tests whether typo location changes performance.
# Uses severity 1 and 2 because these levels achieved 100% completion in the pilot.

In [14]:
!python capstone_robustness.py \
  --task squad \
  --backend hf \
  --model Qwen/Qwen3-4B \
  --n_samples 200 \
  --seed 42 \
  --typo_types keyboard deletion transposition \
  --match_typo_targets \
  --locations any \
  --severities 1 2 3 \
  --typo_difficulty hard \
  --keyword_strategy idf \
  --output results/qwen_squad_core.csv

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Design: 9 corrupted conditions + 1 matched clean condition(s); 2,000 total generations.
Loading weights: 100% 398/398 [00:29<00:00, 13.44it/s]
Running clean baseline | mitigation=none on 200 squad examples...
100% 200/200 [04:10<00:00,  1.25s/it]
Running keyboard | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1

=== PRIMARY SUMMARY ===
        model  task  severity typo_difficulty mitigation   n  requested_n  excluded_examples_due_to_errors  clean_score    score  absolute_drop  drop_ci_2.5  drop_ci_97.5  bootstrap_probability_drop_le_zero
Qwen/Qwen3-4B squad         1            hard       none 200          200                                0     0.874738 0.837997       0.036741     0.014095      0.061463                                 0.0
Qwen/Qwen3-4B squad         2            hard       none 200          200                                0     0.874738 0.794850       0.079889     0.047510      0.114696                                 0.0
Qwen/Qwen3-4B squad         3            hard       none 200          200                                0     0.874738 0.747091       0.127648     0.088126      0.168388                                 0.0

The full condition-level summary was written to disk; use it for secondary typo-type/location analyses.

Raw results: results/qwen_squad_core.csv
Summary:     results/qwen_squad_core_summary.csv
Primary:     results/qwen_squad_core_primary_summary.csv
Metadata:    results/qwen_squad_core_metadata.json

In [5]:
from huggingface_hub import login, whoami

login()
print(whoami())

{'type': 'user', 'id': '662ff1640a30d52cb36db0d8', 'name': 'jessicahung', 'fullname': 'Jessica Hung', 'canPay': False, 'billingMode': 'prepaid', 'periodEnd': 1790812800, 'isPro': False, 'avatarUrl': '/avatars/4c22f136af4f7701d9523e48a211ae2c.svg', 'orgs': [], 'auth': {'type': 'oauth', 'expiresAt': '2026-10-23T17:25:56.000Z'}}

In [17]:
!python capstone_robustness.py \
  --task squad \
  --backend hf \
  --model meta-llama/Llama-3.2-3B-Instruct \
  --n_samples 200 \
  --seed 42 \
  --typo_types keyboard deletion transposition \
  --match_typo_targets \
  --locations any \
  --severities 1 2 3 \
  --typo_difficulty hard \
  --keyword_strategy idf \
  --output results/llama_squad_core.csv

Design: 9 corrupted conditions + 1 matched clean condition(s); 2,000 total generations.
config.json: 100% 878/878 [00:00<00:00, 2.25MB/s]
tokenizer_config.json: 100% 54.5k/54.5k [00:00<00:00, 71.2MB/s]
tokenizer.json: 100% 9.09M/9.09M [00:00<00:00, 37.6MB/s]
special_tokens_map.json: 100% 296/296 [00:00<00:00, 1.35MB/s]
model.safetensors.index.json: 100% 20.9k/20.9k [00:00<00:00, 52.5MB/s]
Downloading bytes:           |  0.00B
Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0% 0/2 [00:00<?, ?it/s]
Reconstructing (incomplete total...):   0% 0.00/6.43G [00:00<?, ?B/s]
Downloading bytes:   4% 234M/6.43G [00:01<00:27, 227MB/s,  222MB/s  ]
Downloading bytes:   5% 300M/6.43G [00:01<00:40, 151MB/s,  163MB/s  ]
Downloading bytes:  22% 1.40G/6.43G [00:07<00:21, 232MB/s,  220MB/s  ]
Downloading bytes:  24% 1.53G/6.43G [00:07<00:20, 237MB/s,  207MB/s  ]
Downloading bytes:  49% 3.14G/6.43G [00:12<00:09, 349MB/s,  352MB/s  ]
Downloading bytes:  49% 3.17G/6.43G [00:26<00:09, 349MB/s,  349MB/s  ]
Downloading bytes:  51% 3.30G/6.43G [01:02<04:58, 10.5MB/s, 7.37MB/s  ]
Downloading bytes:  58% 3.70G/6.43G [01:16<00:18, 151MB/s,  151MB/s  ]
Reconstructing (incomplete total...):  19% 1.25G/6.43G [01:16<04:24, 19.6MB/s, 19.6MB/s  ]
Downloading bytes:  58% 3.74G/6.43G [01:17<04:57, 9.03MB/s, 6.29MB/s  ]
Downloading bytes:  74% 4.74G/6.43G [01:31<00:05, 305MB/s,  305MB/s  ]
Reconstructing (incomplete total...):  37% 2.39G/6.43G [01:31<01:31, 44.0MB/s, 44.0MB/s  ]
Reconstructing (incomplete total...):  45% 2.92G/6.43G [01:41<01:48, 32.2MB/s, 44.0MB/s  ]

Downloading bytes:  79% 5.06G/6.43G [01:43<00:12, 109MB/s, 88.1MB/s  ]
Downloading bytes:  85% 5.48G/6.43G [01:45<00:04, 189MB/s,  175MB/s  ]
Downloading bytes:  86% 5.55G/6.43G [01:46<00:06, 138MB/s,  137MB/s  ]
Reconstructing (incomplete total...):  76% 4.90G/6.43G [01:47<00:16, 92.4MB/s, 74.6MB/s  ]
Reconstructing (incomplete total...):  84% 5.41G/6.43G [01:51<00:10, 100MB/s, 92.4MB/s  ]
Downloading bytes:  86% 5.55G/6.43G [01:56<00:06, 138MB/s,  138MB/s  ]
Reconstructing (incomplete total...): 100% 6.43G/6.43G [02:02<00:00, 94.4MB/s,  114MB/s  ]

Fetching 2 files: 100% 2/2 [02:02<00:00, 61.06s/it]
Download complete: 100% 5.55G/5.55G [02:02<00:00, 138MB/s,  138MB/s  ]
Reconstruction complete: 100% 6.43G/6.43G [02:02<00:00, 52.6MB/s, 94.4MB/s  ]
Download complete: 100% 5.55G/5.55G [02:02<00:00, 45.5MB/s,  138MB/s  ]
Loading weights: 100% 254/254 [00:19<00:00, 13.20it/s]
generation_config.json: 100% 189/189 [00:00<00:00, 844kB/s]
Running clean baseline | mitigation=none on 200 squad examples...
  0% 0/200 [00:00<?, ?it/s][transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
100% 200/200 [02:59<00:00,  1.11it/s]
Running keyboard | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1

=== PRIMARY SUMMARY ===
                           model  task  severity typo_difficulty mitigation   n  requested_n  excluded_examples_due_to_errors  clean_score    score  absolute_drop  drop_ci_2.5  drop_ci_97.5  bootstrap_probability_drop_le_zero
meta-llama/Llama-3.2-3B-Instruct squad         1            hard       none 200          200                                0     0.865947 0.816686       0.049261     0.020519      0.081054                              0.0004
meta-llama/Llama-3.2-3B-Instruct squad         2            hard       none 200          200                                0     0.865947 0.713608       0.152339     0.114026      0.194385                              0.0000
meta-llama/Llama-3.2-3B-Instruct squad         3            hard       none 200          200                                0     0.865947 0.663464       0.202483     0.154702      0.249316                              0.0000

The full condition-level summary was written to disk; use it for secondary typo-type/location analyses.

Raw results: results/llama_squad_core.csv
Summary:     results/llama_squad_core_summary.csv
Primary:     results/llama_squad_core_primary_summary.csv
Metadata:    results/llama_squad_core_metadata.json

In [18]:
llama_summary = pd.read_csv("results/llama_squad_core_summary.csv")

display(
    llama_summary[
        [
            "typo_type",
            "severity",
            "error_rate",
            "mean_actual_severity",
            "severity_completion_rate",
            "mean_actual_char_operations",
        ]
    ]
)

,typo_type,severity,error_rate,mean_actual_severity,severity_completion_rate,mean_actual_char_operations
0,deletion,1,0.0,1.000,1.000,2.00
1,deletion,2,0.0,2.000,1.000,4.00
2,deletion,3,0.0,2.975,0.975,5.95
3,keyboard,1,0.0,1.000,1.000,2.00
4,keyboard,2,0.0,2.000,1.000,4.00
5,keyboard,3,0.0,2.975,0.975,5.95
6,transposition,1,0.0,1.000,1.000,2.00
7,transposition,2,0.0,2.000,1.000,4.00
8,transposition,3,0.0,2.975,0.975,5.95

In [19]:
!python compare_models.py \
  --inputs \
    results/qwen_squad_core.csv \
    results/llama_squad_core.csv \
  --mitigation none \
  --typo_difficulty hard \
  --bootstrap_samples 5000 \
  --seed 42 \
  --output_dir results/qwen_vs_llama_core

Saved paired cross-model comparison to results/qwen_vs_llama_core. Positive model gaps mean model A degraded more than model B.

In [20]:
gap = pd.read_csv(
    "results/qwen_vs_llama_core/cross_model_gap_by_severity.csv"
)

display(gap)

,model_a,model_b,gap_definition,severity,mean_gap,gap_ci_2.5,gap_ci_97.5,n_examples
0,Qwen3-4B,Llama-3.2-3B-Instruct,drop_model_a_minus_drop_model_b,1,-0.012520,-0.045522,0.021553,200
1,Qwen3-4B,Llama-3.2-3B-Instruct,drop_model_a_minus_drop_model_b,2,-0.072451,-0.116299,-0.029456,200
2,Qwen3-4B,Llama-3.2-3B-Instruct,drop_model_a_minus_drop_model_b,3,-0.074835,-0.122977,-0.027007,200

In [21]:
condition_gaps = pd.read_csv(
    "results/qwen_vs_llama_core/cross_model_gap_by_condition.csv"
)

display(
    condition_gaps[
        [
            "typo_type",
            "severity",
            "mean_gap",
            "gap_ci_2.5",
            "gap_ci_97.5",
            "n_examples",
        ]
    ]
)

       typo_type  severity  mean_gap  gap_ci_2.5  gap_ci_97.5  n_examples
0       deletion         1 -0.020007   -0.058967     0.016849         200
1       deletion         2 -0.063931   -0.117309    -0.011372         200
2       deletion         3 -0.090085   -0.151343    -0.027165         200
3       keyboard         1 -0.038765   -0.086578     0.009136         200
4       keyboard         2 -0.122764   -0.183530    -0.065123         200
5       keyboard         3 -0.056992   -0.115733     0.000935         200
6  transposition         1  0.021212   -0.014727     0.057638         200
7  transposition         2 -0.030657   -0.080563     0.020206         200
8  transposition         3 -0.077429   -0.136356    -0.019541         200

In [22]:
!python capstone_robustness.py \
  --task squad \
  --backend hf \
  --model Qwen/Qwen3-4B \
  --n_samples 200 \
  --seed 42 \
  --typo_types keyboard deletion transposition \
  --match_typo_targets \
  --locations beginning middle end keyword \
  --severities 1 \
  --typo_difficulty standard \
  --keyword_strategy idf \
  --output results/qwen_squad_positions_standard.csv

Design: 12 corrupted conditions + 1 matched clean condition(s); 2,600 total generations.
Loading weights: 100% 398/398 [00:30<00:00, 13.25it/s]
Running clean baseline | mitigation=none on 200 squad examples...
100% 200/200 [04:11<00:00,  1.26s/it]
Running keyboard | beginning | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running keyboard | middle | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running keyboard | end | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running keyboard | keyword | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running deletion | beginning | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running deletion | middle | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running deletion | end | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running deletion | keyword | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running transposition | beginning | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running transposition | middle | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running transposition | end | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running transposition | keyword | severity=1 | difficulty=standard | mitigation=none | replicate=1/1

=== PRIMARY SUMMARY ===
        model  task  severity typo_difficulty mitigation   n  requested_n  excluded_examples_due_to_errors  clean_score    score  absolute_drop  drop_ci_2.5  drop_ci_97.5  bootstrap_probability_drop_le_zero
Qwen/Qwen3-4B squad         1        standard       none 200          200                                0     0.874738 0.862092       0.012647     0.002878       0.02338                               0.005

The full condition-level summary was written to disk; use it for secondary typo-type/location analyses.

Raw results: results/qwen_squad_positions_standard.csv
Summary:     results/qwen_squad_positions_standard_summary.csv
Primary:     results/qwen_squad_positions_standard_primary_summary.csv
Metadata:    results/qwen_squad_positions_standard_metadata.json

In [25]:
positions = pd.read_csv(
    "results/qwen_squad_positions_standard_summary.csv"
)

display(
    positions[
        [
            "typo_type",
            "location",
            "severity",
            "error_rate",
            "mean_actual_severity",
            "severity_completion_rate",
            "mean_actual_char_operations",
        ]
    ]
)

print(positions['mean_actual_severity'], positions['mean_actual_char_operations'], positions['error_rate'])

print(
    "Minimum completion rate:",
    positions["severity_completion_rate"].min(),
)

,typo_type,location,severity,error_rate,mean_actual_severity,severity_completion_rate,mean_actual_char_operations
0,deletion,beginning,1,0.0,1.0,1.0,1.0
1,deletion,end,1,0.0,1.0,1.0,1.0
2,deletion,keyword,1,0.0,1.0,1.0,1.0
3,deletion,middle,1,0.0,1.0,1.0,1.0
4,keyboard,beginning,1,0.0,1.0,1.0,1.0
5,keyboard,end,1,0.0,1.0,1.0,1.0
6,keyboard,keyword,1,0.0,1.0,1.0,1.0
7,keyboard,middle,1,0.0,1.0,1.0,1.0
8,transposition,beginning,1,0.0,1.0,1.0,1.0
9,transposition,end,1,0.0,1.0,1.0,1.0
10,transposition,keyword,1,0.0,1.0,1.0,1.0
11,transposition,middle,1,0.0,1.0,1.0,1.0

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
Name: mean_actual_severity, dtype: float64 0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    1.0
Name: mean_actual_char_operations, dtype: float64 0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
5     0.0
6     0.0
7     0.0
8     0.0
9     0.0
10    0.0
11    0.0
Name: error_rate, dtype: float64
Minimum completion rate: 1.0

In [26]:
!python capstone_robustness.py \
  --task squad \
  --backend hf \
  --model meta-llama/Llama-3.2-3B-Instruct \
  --n_samples 200 \
  --seed 42 \
  --typo_types keyboard deletion transposition \
  --match_typo_targets \
  --locations beginning middle end keyword \
  --severities 1 \
  --typo_difficulty standard \
  --keyword_strategy idf \
  --output results/llama_squad_positions_standard.csv

Design: 12 corrupted conditions + 1 matched clean condition(s); 2,600 total generations.
Loading weights: 100% 254/254 [00:20<00:00, 12.63it/s]
Running clean baseline | mitigation=none on 200 squad examples...
  0% 0/200 [00:00<?, ?it/s][transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
100% 200/200 [03:02<00:00,  1.09it/s]
Running keyboard | beginning | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running keyboard | middle | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running keyboard | end | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running keyboard | keyword | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running deletion | beginning | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running deletion | middle | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running deletion | end | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running deletion | keyword | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running transposition | beginning | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running transposition | middle | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running transposition | end | severity=1 | difficulty=standard | mitigation=none | replicate=1/1
Running transposition | keyword | severity=1 | difficulty=standard | mitigation=none | replicate=1/1

=== PRIMARY SUMMARY ===
                           model  task  severity typo_difficulty mitigation   n  requested_n  excluded_examples_due_to_errors  clean_score    score  absolute_drop  drop_ci_2.5  drop_ci_97.5  bootstrap_probability_drop_le_zero
meta-llama/Llama-3.2-3B-Instruct squad         1        standard       none 200          200                                0     0.865947 0.848248       0.017699    -0.000821      0.036704                              0.0312

The full condition-level summary was written to disk; use it for secondary typo-type/location analyses.

Raw results: results/llama_squad_positions_standard.csv
Summary:     results/llama_squad_positions_standard_summary.csv
Primary:     results/llama_squad_positions_standard_primary_summary.csv
Metadata:    results/llama_squad_positions_standard_metadata.json

In [4]:
!python compare_models.py \
  --inputs \
    results/qwen_squad_positions_standard.csv \
    results/llama_squad_positions_standard.csv \
  --mitigation none \
  --typo_difficulty standard \
  --bootstrap_samples 5000 \
  --seed 42 \
  --output_dir results/qwen_vs_llama_positions_standard

Saved paired cross-model comparison to results/qwen_vs_llama_positions_standard. Positive model gaps mean model A degraded more than model B.

In [6]:
display(
    pd.read_csv(
        "results/qwen_vs_llama_positions_standard/"
        "cross_model_gap_by_severity.csv"
    )
)

,model_a,model_b,gap_definition,severity,mean_gap,gap_ci_2.5,gap_ci_97.5,n_examples
0,Qwen3-4B,Llama-3.2-3B-Instruct,drop_model_a_minus_drop_model_b,1,-0.005053,-0.02405,0.01386,200

In [7]:
position_gaps = pd.read_csv(
    "results/qwen_vs_llama_positions_standard/"
    "cross_model_gap_by_condition.csv"
)

display(
    position_gaps[
        [
            "typo_type",
            "location",
            "mean_gap",
            "gap_ci_2.5",
            "gap_ci_97.5",
            "n_examples",
        ]
    ]
)

        typo_type   location  mean_gap  gap_ci_2.5  gap_ci_97.5  n_examples
0        deletion  beginning -0.012137   -0.041824     0.017389         200
1        deletion        end -0.005928   -0.033876     0.021741         200
2        deletion    keyword  0.008757   -0.014991     0.033036         200
3        deletion     middle -0.015419   -0.045329     0.013633         200
4        keyboard  beginning  0.018954   -0.014134     0.054127         200
5        keyboard        end -0.021518   -0.058139     0.014061         200
6        keyboard    keyword  0.007360   -0.019010     0.034548         200
7        keyboard     middle -0.023140   -0.055091     0.008842         200
8   transposition  beginning  0.005412   -0.025464     0.036564         200
9   transposition        end -0.022043   -0.054552     0.008744         200
10  transposition    keyword  0.006953   -0.019251     0.035466         200
11  transposition     middle -0.007885   -0.037623     0.019615         200

In [8]:
!python capstone_visualizations.py \
  --input results/qwen_squad_core.csv \
  --model Qwen/Qwen3-4B \
  --embedding_backend hf \
  --embedding_typo keyboard \
  --embedding_location any \
  --embedding_samples 40 \
  --batch_size 4 \
  --projection pca \
  --mitigation none \
  --typo_difficulty hard \
  --output_dir results/qwen_core_embedding_figures

Saved performance plots to results/qwen_core_embedding_figures
config.json: 100% 726/726 [00:00<00:00, 3.94MB/s]
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
tokenizer_config.json: 100% 9.73k/9.73k [00:00<00:00, 26.4MB/s]
vocab.json: 100% 2.78M/2.78M [00:00<00:00, 60.5MB/s]
merges.txt: 100% 1.67M/1.67M [00:00<00:00, 123MB/s]

tokenizer.json: downloading bytes:  14% 1.59M/11.4M [00:00<00:03, 2.69MB/s]
tokenizer.json: downloading bytes: 100% 3.40M/3.40M [00:00<00:00, 5.47MB/s,  335kB/s  ]
tokenizer.json: reconstructing file: 100% 11.4M/11.4M [00:00<00:00, 18.4MB/s, 1.13MB/s  ]
Loading Qwen/Qwen3-4B to extract contextual representations...
model.safetensors.index.json: 100% 32.8k/32.8k [00:00<00:00, 79.9MB/s]
Downloading bytes:           |  0.00B
Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 3 files:   0% 0/3 [00:00<?, ?it/s]
Reconstructing (incomplete total...):   0% 0.00/3.99G [00:00<?, ?B/s]
Reconstructing (incomplete total...):   0% 0.00/8.04G [00:00<?, ?B/s]
Downloading bytes:   3% 222M/8.04G [00:01<00:30, 261MB/s,  285MB/s  ]
Reconstructing (incomplete total...):   1% 49.8M/8.04G [00:01<03:02, 43.9MB/s]
Downloading bytes:   4% 326M/8.04G [00:01<00:30, 254MB/s,  257MB/s  ]
Downloading bytes:   4% 360M/8.04G [00:01<00:35, 219MB/s,  254MB/s  ]
Reconstructing (incomplete total...):   4% 356M/8.04G [00:01<00:30, 254MB/s,  181MB/s  ]

Downloading bytes:   9% 746M/8.04G [00:03<00:22, 326MB/s,  308MB/s  ]
Downloading bytes:  11% 891M/8.04G [00:03<00:26, 270MB/s,  322MB/s  ]
Downloading bytes:  12% 927M/8.04G [00:03<00:37, 192MB/s,  270MB/s  ]
Downloading bytes:  15% 1.24G/8.04G [00:05<00:36, 188MB/s,  183MB/s  ]
Downloading bytes:  17% 1.35G/8.04G [00:06<00:36, 182MB/s,  170MB/s  ]
Downloading bytes:  20% 1.59G/8.04G [00:06<00:23, 277MB/s,  271MB/s  ]
Downloading bytes:  21% 1.65G/8.04G [00:07<00:30, 211MB/s,  248MB/s  ]
Downloading bytes:  23% 1.85G/8.04G [00:08<00:29, 211MB/s,  247MB/s  ]
Downloading bytes:  26% 2.08G/8.04G [00:08<00:20, 294MB/s,  286MB/s  ]
Downloading bytes:  28% 2.24G/8.04G [00:09<00:35, 162MB/s,  171MB/s  ]
Downloading bytes:  28% 2.26G/8.04G [00:10<00:45, 128MB/s,  162MB/s  ]
Downloading bytes:  34% 2.73G/8.04G [00:12<00:29, 183MB/s,  216MB/s  ]
Downloading bytes:  39% 3.15G/8.04G [00:15<00:40, 121MB/s,  116MB/s  ]
Downloading bytes:  42% 3.41G/8.04G [00:16<00:18, 251MB/s,  229MB/s  ]
Downloading bytes:  58% 4.70G/8.04G [00:20<00:10, 306MB/s,  291MB/s  ]
Downloading bytes:  59% 4.74G/8.04G [00:21<00:14, 221MB/s,  306MB/s  ]
Downloading bytes:  59% 4.78G/8.04G [00:21<00:16, 201MB/s,  221MB/s  ]
Downloading bytes:  61% 4.93G/8.04G [00:22<00:19, 159MB/s,  160MB/s  ]
Downloading bytes:  69% 5.55G/8.04G [00:24<00:08, 300MB/s,  292MB/s  ]
Downloading bytes:  73% 5.91G/8.04G [00:31<00:08, 249MB/s,  221MB/s  ]
Downloading bytes:  79% 6.36G/8.04G [00:35<00:07, 212MB/s,  192MB/s  ]
Downloading bytes:  83% 6.70G/8.04G [00:38<00:07, 182MB/s,  176MB/s  ]
Downloading bytes:  87% 7.01G/8.04G [00:54<00:05, 197MB/s,  197MB/s  ]
Reconstructing (incomplete total...):  66% 5.27G/8.04G [00:54<00:20, 135MB/s,  135MB/s  ]
Reconstructing (incomplete total...):  73% 5.85G/8.04G [00:55<00:33, 66.1MB/s,  135MB/s  ]
Reconstructing (incomplete total...):  79% 6.37G/8.04G [01:04<00:26, 63.9MB/s, 66.1MB/s  ]
Reconstructing (incomplete total...):  86% 6.95G/8.04G [01:06<00:12, 85.2MB/s, 63.9MB/s  ]
Reconstructing (incomplete total...):  93% 7.49G/8.04G [01:13<00:06, 81.5MB/s, 85.2MB/s  ]
Reconstructing (incomplete total...):  94% 7.59G/8.04G [01:14<00:05, 84.3MB/s, 81.5MB/s  ]

Fetching 3 files:  67% 2/3 [01:14<00:43, 43.58s/it]
Reconstructing (incomplete total...): 100% 8.04G/8.04G [01:15<00:00, 120MB/s, 84.3MB/s  ]

Fetching 3 files: 100% 3/3 [01:15<00:00, 25.07s/it]
Download complete: 100% 7.01G/7.01G [01:15<00:00, 197MB/s,  197MB/s  ]
Reconstruction complete: 100% 8.04G/8.04G [01:15<00:00, 107MB/s,  120MB/s  ]
Download complete: 100% 7.01G/7.01G [01:15<00:00, 93.0MB/s,  197MB/s  ]
Loading weights: 100% 398/398 [00:27<00:00, 14.29it/s]
Saved embedding and tokenization analysis to results/qwen_core_embedding_figures

In [9]:
!python capstone_visualizations.py \
  --input results/llama_squad_core.csv \
  --model meta-llama/Llama-3.2-3B-Instruct \
  --embedding_backend hf \
  --embedding_typo keyboard \
  --embedding_location any \
  --embedding_samples 40 \
  --batch_size 4 \
  --projection pca \
  --mitigation none \
  --typo_difficulty hard \
  --output_dir results/llama_core_embedding_figures

Saved performance plots to results/llama_core_embedding_figures
Loading meta-llama/Llama-3.2-3B-Instruct to extract contextual representations...
Loading weights: 100% 254/254 [00:08<00:00, 29.90it/s]
Saved embedding and tokenization analysis to results/llama_core_embedding_figures

In [10]:
!python capstone_robustness.py \
  --task squad \
  --backend hf \
  --model meta-llama/Llama-3.2-3B-Instruct \
  --n_samples 200 \
  --seed 42 \
  --typo_types keyboard deletion transposition \
  --match_typo_targets \
  --locations any \
  --severities 2 3 \
  --typo_difficulty hard \
  --keyword_strategy idf \
  --mitigations none self_correct \
  --output results/llama_squad_mitigation.csv

README.md: 100% 7.62k/7.62k [00:00<00:00, 1.95MB/s]

plain_text/train-00000-of-00001.parquet: downloading bytes:  29% 4.19M/14.5M [00:01<00:03, 3.26MB/s]
plain_text/train-00000-of-00001.parquet: downloading bytes: 100% 14.2M/14.2M [00:01<00:00, 9.56MB/s, 1.36MB/s  ]
plain_text/train-00000-of-00001.parquet: reconstructing file: 100% 14.5M/14.5M [00:01<00:00, 9.74MB/s, 1.39MB/s  ]

plain_text/validation-00000-of-00001.par(…): downloading bytes:   0% 0.00/1.82M [00:00<?, ?B/s]
plain_text/validation-00000-of-00001.par(…): downloading bytes: 100% 1.79M/1.79M [00:01<00:00, 1.63MB/s,  174kB/s  ]
plain_text/validation-00000-of-00001.par(…): reconstructing file: 100% 1.82M/1.82M [00:01<00:00, 1.65MB/s,  177kB/s  ]
Generating train split: 100% 87599/87599 [00:00<00:00, 370759.98 examples/s]
Generating validation split: 100% 10570/10570 [00:00<00:00, 463757.16 examples/s]
Design: 12 corrupted conditions + 2 matched clean condition(s); 2,800 total generations.
Loading weights: 100% 254/254 [00:18<00:00, 13.82it/s]
generation_config.json: 100% 189/189 [00:00<00:00, 882kB/s]
Running clean baseline | mitigation=none on 200 squad examples...
  0% 0/200 [00:00<?, ?it/s][transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
100% 200/200 [03:06<00:00,  1.07it/s]
Running clean baseline | mitigation=self_correct on 200 squad examples...
100% 200/200 [03:22<00:00,  1.01s/it]
Running keyboard | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=2 | difficulty=hard | mitigation=self_correct | replicate=1/1
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=3 | difficulty=hard | mitigation=self_correct | replicate=1/1
Running deletion | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=2 | difficulty=hard | mitigation=self_correct | replicate=1/1
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=3 | difficulty=hard | mitigation=self_correct | replicate=1/1
Running transposition | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=2 | difficulty=hard | mitigation=self_correct | replicate=1/1
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=3 | difficulty=hard | mitigation=self_correct | replicate=1/1

=== PRIMARY SUMMARY ===
                           model  task  severity typo_difficulty   mitigation   n  requested_n  excluded_examples_due_to_errors  clean_score    score  absolute_drop  drop_ci_2.5  drop_ci_97.5  bootstrap_probability_drop_le_zero
meta-llama/Llama-3.2-3B-Instruct squad         2            hard         none 200          200                                0     0.870886 0.720921       0.149966     0.111340      0.191646                                 0.0
meta-llama/Llama-3.2-3B-Instruct squad         2            hard self_correct 200          200                                0     0.843778 0.718439       0.125339     0.081225      0.172957                                 0.0
meta-llama/Llama-3.2-3B-Instruct squad         3            hard         none 200          200                                0     0.870886 0.668221       0.202665     0.153927      0.250689                                 0.0
meta-llama/Llama-3.2-3B-Instruct squad         3            hard self_correct 200          200                                0     0.843778 0.651731       0.192047     0.141568      0.242413                                 0.0

The full condition-level summary was written to disk; use it for secondary typo-type/location analyses.

Raw results: results/llama_squad_mitigation.csv
Summary:     results/llama_squad_mitigation_summary.csv
Primary:     results/llama_squad_mitigation_primary_summary.csv
Mitigation:  results/llama_squad_mitigation_mitigation_summary.csv
Metadata:    results/llama_squad_mitigation_metadata.json

In [12]:
import pandas as pd

mitigation = pd.read_csv(
    "results/llama_squad_mitigation_mitigation_summary.csv"
)

display(
    mitigation[
        [
            "typo_type",
            "severity",
            "n",
            "unmitigated_score",
            "self_correct_score",
            "mean_improvement",
            "improvement_ci_2.5",
            "improvement_ci_97.5",
            "bootstrap_probability_improvement_le_zero",
        ]
    ]
)

,typo_type,severity,n,unmitigated_score,self_correct_score,mean_improvement,improvement_ci_2.5,improvement_ci_97.5,bootstrap_probability_improvement_le_zero
0,deletion,2,200,0.718048,0.717696,-0.000352,-0.035752,0.037579,0.5072
1,deletion,3,200,0.673563,0.653895,-0.019668,-0.061150,0.020979,0.8310
2,keyboard,2,200,0.665385,0.699758,0.034374,0.004831,0.066278,0.0108
3,keyboard,3,200,0.631088,0.637070,0.005982,-0.034273,0.046676,0.3782
4,transposition,2,200,0.779330,0.737863,-0.041467,-0.076770,-0.007987,0.9938
5,transposition,3,200,0.700013,0.664227,-0.035786,-0.080493,0.007543,0.9468

In [13]:
!python capstone_robustness.py \
  --task gsm8k \
  --backend hf \
  --model Qwen/Qwen3-4B \
  --n_samples 100 \
  --seed 42 \
  --typo_types keyboard deletion transposition \
  --match_typo_targets \
  --locations any \
  --severities 1 2 3 \
  --typo_difficulty hard \
  --max_new_tokens 512 \
  --output results/qwen_gsm8k_core.csv

README.md: 100% 7.93k/7.93k [00:00<00:00, 1.78MB/s]

main/train-00000-of-00001.parquet: downloading bytes:   0% 0.00/2.31M [00:00<?, ?B/s]
main/train-00000-of-00001.parquet: downloading bytes: 100% 2.30M/2.30M [00:01<00:00, 2.05MB/s,  223kB/s  ]
main/train-00000-of-00001.parquet: reconstructing file: 100% 2.31M/2.31M [00:01<00:00, 2.05MB/s,  224kB/s  ]

main/test-00000-of-00001.parquet: downloading bytes:   0% 0.00/419k [00:00<?, ?B/s]
main/test-00000-of-00001.parquet: downloading bytes: 100% 419k/419k [00:01<00:00, 399kB/s, 40.8kB/s  ]
main/test-00000-of-00001.parquet: reconstructing file: 100% 419k/419k [00:01<00:00, 399kB/s, 40.8kB/s  ]
Generating train split: 100% 7473/7473 [00:00<00:00, 352144.54 examples/s]
Generating test split: 100% 1319/1319 [00:00<00:00, 308600.82 examples/s]
Design: 9 corrupted conditions + 1 matched clean condition(s); 1,000 total generations.
config.json: 100% 726/726 [00:00<00:00, 2.79MB/s]
tokenizer_config.json: 100% 9.73k/9.73k [00:00<00:00, 8.01MB/s]
vocab.json: 100% 2.78M/2.78M [00:00<00:00, 10.9MB/s]
merges.txt: 100% 1.67M/1.67M [00:00<00:00, 2.34MB/s]

tokenizer.json: downloading bytes:   0% 0.00/11.4M [00:00<?, ?B/s]
tokenizer.json: downloading bytes: 100% 3.40M/3.40M [00:01<00:00, 3.09MB/s,  330kB/s  ]
tokenizer.json: reconstructing file: 100% 11.4M/11.4M [00:01<00:00, 10.4MB/s, 1.11MB/s  ]
model.safetensors.index.json: 100% 32.8k/32.8k [00:00<00:00, 71.9MB/s]
Downloading bytes:           |  0.00B
Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 3 files:   0% 0/3 [00:00<?, ?it/s]
Reconstructing (incomplete total...):   0% 0.00/3.99G [00:00<?, ?B/s]
Reconstructing (incomplete total...):   0% 0.00/8.04G [00:00<?, ?B/s]
Downloading bytes:   2% 147M/8.04G [00:01<00:50, 155MB/s,  120MB/s  ]
Downloading bytes:   2% 177M/8.04G [00:01<00:51, 152MB/s,  155MB/s  ]
Downloading bytes:   3% 225M/8.04G [00:02<00:59, 131MB/s,  163MB/s  ]
Downloading bytes:   4% 351M/8.04G [00:03<00:48, 157MB/s,  169MB/s  ]
Downloading bytes:   7% 528M/8.04G [00:03<00:35, 212MB/s,  205MB/s  ]
Downloading bytes:  13% 1.01G/8.04G [00:06<00:30, 229MB/s,  205MB/s  ]
Downloading bytes:  14% 1.10G/8.04G [00:06<00:23, 302MB/s,  294MB/s  ]
Downloading bytes:  17% 1.33G/8.04G [00:07<00:29, 231MB/s,  252MB/s  ]
Downloading bytes:  29% 2.36G/8.04G [00:11<00:29, 195MB/s,  268MB/s  ]
Downloading bytes:  32% 2.58G/8.04G [00:12<00:23, 234MB/s,  219MB/s  ]
Downloading bytes:  33% 2.63G/8.04G [00:12<00:29, 182MB/s,  180MB/s  ]
Downloading bytes:  34% 2.74G/8.04G [00:13<00:34, 155MB/s,  161MB/s  ]
Reconstructing (incomplete total...):  15% 1.24G/8.04G [00:13<01:05, 104MB/s,  105MB/s  ]

Downloading bytes:  44% 3.51G/8.04G [00:16<00:21, 211MB/s,  213MB/s  ]
Reconstructing (incomplete total...):  22% 1.74G/8.04G [00:17<00:54, 116MB/s,  104MB/s  ]
Downloading bytes:  47% 3.75G/8.04G [00:19<00:33, 127MB/s,  127MB/s  ]
Downloading bytes:  48% 3.87G/8.04G [00:20<00:45, 90.9MB/s, 90.9MB/s  ]
Downloading bytes:  49% 3.91G/8.04G [00:20<00:36, 113MB/s,  106MB/s  ]
Downloading bytes:  55% 4.40G/8.04G [00:23<00:39, 93.2MB/s,  127MB/s  ]
Downloading bytes:  64% 5.18G/8.04G [00:27<00:08, 335MB/s,  322MB/s  ]
Downloading bytes:  65% 5.25G/8.04G [00:27<00:18, 150MB/s,  159MB/s  ]
Downloading bytes:  67% 5.37G/8.04G [00:28<00:15, 169MB/s,  162MB/s  ]
Downloading bytes:  72% 5.83G/8.04G [00:29<00:07, 316MB/s,  344MB/s  ]
Downloading bytes:  80% 6.42G/8.04G [00:32<00:05, 315MB/s,  304MB/s  ]
Downloading bytes:  83% 6.69G/8.04G [00:34<00:05, 258MB/s,  235MB/s  ]
Downloading bytes:  85% 6.87G/8.04G [00:44<00:26, 43.8MB/s, 31.2MB/s  ]
Downloading bytes:  87% 7.01G/8.04G [00:45<00:10, 97.1MB/s, 88.4MB/s  ]
Reconstructing (incomplete total...):  78% 6.28G/8.04G [00:49<00:15, 116MB/s,  115MB/s  ]
Reconstructing (incomplete total...):  85% 6.83G/8.04G [00:53<00:09, 126MB/s,  116MB/s  ]
Reconstructing (incomplete total...):  86% 6.88G/8.04G [00:57<00:13, 84.9MB/s,  126MB/s  ]

Downloading bytes:  87% 7.01G/8.04G [00:58<00:10, 97.1MB/s, 97.1MB/s  ]
Reconstructing (incomplete total...):  92% 7.41G/8.04G [00:58<00:05, 127MB/s, 84.9MB/s  ]
Reconstructing (incomplete total...):  99% 7.95G/8.04G [01:02<00:00, 134MB/s,  127MB/s  ]
Reconstructing (incomplete total...): 100% 8.04G/8.04G [01:02<00:00, 142MB/s,  134MB/s  ]

Fetching 3 files: 100% 3/3 [01:02<00:00, 20.96s/it]
Download complete: 100% 7.01G/7.01G [01:02<00:00, 97.1MB/s, 97.1MB/s  ]
Download complete: 100% 7.01G/7.01G [01:02<00:00, 111MB/s, 97.1MB/s  ]
Reconstruction complete: 100% 8.04G/8.04G [01:02<00:00, 128MB/s,  142MB/s  ]
Loading weights: 100% 398/398 [00:32<00:00, 12.33it/s]
generation_config.json: 100% 239/239 [00:00<00:00, 1.10MB/s]
Running clean baseline | mitigation=none on 100 gsm8k examples...
100% 100/100 [25:44<00:00, 15.45s/it]
Running keyboard | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1

=== PRIMARY SUMMARY ===
        model  task  severity typo_difficulty mitigation   n  requested_n  excluded_examples_due_to_errors  clean_score    score  absolute_drop  drop_ci_2.5  drop_ci_97.5  bootstrap_probability_drop_le_zero
Qwen/Qwen3-4B gsm8k         1            hard       none 100          100                                0         0.94 0.883333       0.056667     0.020000      0.100000                              0.0002
Qwen/Qwen3-4B gsm8k         2            hard       none 100          100                                0         0.94 0.853333       0.086667     0.036583      0.140000                              0.0004
Qwen/Qwen3-4B gsm8k         3            hard       none 100          100                                0         0.94 0.816667       0.123333     0.070000      0.176667                              0.0000

The full condition-level summary was written to disk; use it for secondary typo-type/location analyses.

Raw results: results/qwen_gsm8k_core.csv
Summary:     results/qwen_gsm8k_core_summary.csv
Primary:     results/qwen_gsm8k_core_primary_summary.csv
Metadata:    results/qwen_gsm8k_core_metadata.json

In [16]:
!python capstone_robustness.py \
  --task gsm8k \
  --backend hf \
  --model meta-llama/Llama-3.2-3B-Instruct \
  --n_samples 100 \
  --seed 42 \
  --typo_types keyboard deletion transposition \
  --match_typo_targets \
  --locations any \
  --severities 1 2 3 \
  --typo_difficulty hard \
  --max_new_tokens 512 \
  --output results/llama_gsm8k_core.csv

Design: 9 corrupted conditions + 1 matched clean condition(s); 1,000 total generations.
Loading weights: 100% 254/254 [00:23<00:00, 10.95it/s]
Running clean baseline | mitigation=none on 100 gsm8k examples...
  0% 0/100 [00:00<?, ?it/s][transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
100% 100/100 [12:32<00:00,  7.53s/it]
Running keyboard | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=1 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=2 | difficulty=hard | mitigation=none | replicate=1/1
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/1

=== PRIMARY SUMMARY ===
                           model  task  severity typo_difficulty mitigation   n  requested_n  excluded_examples_due_to_errors  clean_score    score  absolute_drop   drop_ci_2.5  drop_ci_97.5  bootstrap_probability_drop_le_zero
meta-llama/Llama-3.2-3B-Instruct gsm8k         1            hard       none 100          100                                0         0.79 0.780000       0.010000 -4.333333e-02      0.063333                              0.3360
meta-llama/Llama-3.2-3B-Instruct gsm8k         2            hard       none 100          100                                0         0.79 0.740000       0.050000 -1.000000e-02      0.110000                              0.0448
meta-llama/Llama-3.2-3B-Instruct gsm8k         3            hard       none 100          100                                0         0.79 0.726667       0.063333  1.110223e-17      0.126667                              0.0222

The full condition-level summary was written to disk; use it for secondary typo-type/location analyses.

Raw results: results/llama_gsm8k_core.csv
Summary:     results/llama_gsm8k_core_summary.csv
Primary:     results/llama_gsm8k_core_primary_summary.csv
Metadata:    results/llama_gsm8k_core_metadata.json

In [7]:
display(
    pd.read_csv("results/llama_gsm8k_core_primary_summary.csv")
)

llama_gsm = pd.read_csv("results/llama_gsm8k_core_summary.csv")

display(
    llama_gsm[
        [
            "typo_type",
            "severity",
            "score",
            "error_rate",
            "mean_actual_severity",
            "severity_completion_rate",
            "mean_actual_char_operations",
        ]
    ]
)

,model,task,severity,typo_difficulty,mitigation,n,requested_n,excluded_examples_due_to_errors,clean_score,score,absolute_drop,drop_ci_2.5,drop_ci_97.5,bootstrap_probability_drop_le_zero
0,meta-llama/Llama-3.2-3B-Instruct,gsm8k,1,hard,none,100,100,0,0.79,0.780000,0.010000,-4.333333e-02,0.063333,0.3360
1,meta-llama/Llama-3.2-3B-Instruct,gsm8k,2,hard,none,100,100,0,0.79,0.740000,0.050000,-1.000000e-02,0.110000,0.0448
2,meta-llama/Llama-3.2-3B-Instruct,gsm8k,3,hard,none,100,100,0,0.79,0.726667,0.063333,1.110223e-17,0.126667,0.0222

,typo_type,severity,score,error_rate,mean_actual_severity,severity_completion_rate,mean_actual_char_operations
0,deletion,1,0.77,0.0,1.0,1.0,2.0
1,deletion,2,0.71,0.0,2.0,1.0,4.0
2,deletion,3,0.71,0.0,3.0,1.0,6.0
3,keyboard,1,0.75,0.0,1.0,1.0,2.0
4,keyboard,2,0.73,0.0,2.0,1.0,4.0
5,keyboard,3,0.73,0.0,3.0,1.0,6.0
6,transposition,1,0.82,0.0,1.0,1.0,2.0
7,transposition,2,0.78,0.0,2.0,1.0,4.0
8,transposition,3,0.74,0.0,3.0,1.0,6.0

In [8]:
!python compare_models.py \
  --inputs \
    results/qwen_gsm8k_core.csv \
    results/llama_gsm8k_core.csv \
  --mitigation none \
  --typo_difficulty hard \
  --bootstrap_samples 5000 \
  --seed 42 \
  --output_dir results/qwen_vs_llama_gsm8k

Saved paired cross-model comparison to results/qwen_vs_llama_gsm8k. Positive model gaps mean model A degraded more than model B.

In [10]:
gsm_gap = pd.read_csv(
    "results/qwen_vs_llama_gsm8k/cross_model_gap_by_severity.csv"
)

display(gsm_gap)

,model_a,model_b,gap_definition,severity,mean_gap,gap_ci_2.5,gap_ci_97.5,n_examples
0,Qwen3-4B,Llama-3.2-3B-Instruct,drop_model_a_minus_drop_model_b,1,0.046667,-0.016667,0.113333,100
1,Qwen3-4B,Llama-3.2-3B-Instruct,drop_model_a_minus_drop_model_b,2,0.036667,-0.040000,0.110000,100
2,Qwen3-4B,Llama-3.2-3B-Instruct,drop_model_a_minus_drop_model_b,3,0.060000,-0.003333,0.123333,100

In [9]:
gsm_conditions = pd.read_csv(
    "results/qwen_vs_llama_gsm8k/cross_model_gap_by_condition.csv"
)

display(
    gsm_conditions[
        [
            "typo_type",
            "severity",
            "mean_gap",
            "gap_ci_2.5",
            "gap_ci_97.5",
            "n_examples",
        ]
    ]
)

       typo_type  severity  mean_gap  gap_ci_2.5  gap_ci_97.5  n_examples
0       deletion         1      0.05       -0.03         0.14         100
1       deletion         2      0.02       -0.07         0.11         100
2       deletion         3      0.06       -0.03         0.15         100
3       keyboard         1      0.03       -0.04         0.10         100
4       keyboard         2      0.02       -0.07         0.11         100
5       keyboard         3      0.07       -0.02         0.15         100
6  transposition         1      0.06        0.00         0.13         100
7  transposition         2      0.07       -0.04         0.17         100
8  transposition         3      0.05       -0.04         0.14         100

In [11]:
!python capstone_robustness.py \
  --task squad \
  --backend hf \
  --model Qwen/Qwen3-4B \
  --n_samples 100 \
  --seed 42 \
  --typo_types keyboard deletion transposition \
  --match_typo_targets \
  --locations any \
  --severities 3 \
  --typo_difficulty hard \
  --corruption_replicates 3 \
  --output results/qwen_squad_severity3_replicated.csv

README.md: 100% 7.62k/7.62k [00:00<00:00, 3.12MB/s]

plain_text/train-00000-of-00001.parquet: downloading bytes:  31% 4.49M/14.5M [00:01<00:02, 3.38MB/s]
plain_text/train-00000-of-00001.parquet: downloading bytes: 100% 14.2M/14.2M [00:01<00:00, 10.1MB/s, 1.37MB/s  ]
plain_text/train-00000-of-00001.parquet: reconstructing file: 100% 14.5M/14.5M [00:01<00:00, 10.3MB/s, 1.40MB/s  ]

plain_text/validation-00000-of-00001.par(…): downloading bytes:  98% 1.79M/1.82M [00:01<00:00, 1.60MB/s]
plain_text/validation-00000-of-00001.par(…): downloading bytes: 100% 1.79M/1.79M [00:01<00:00, 1.60MB/s,  174kB/s  ]
plain_text/validation-00000-of-00001.par(…): reconstructing file: 100% 1.82M/1.82M [00:01<00:00, 1.62MB/s,  177kB/s  ]
Generating train split: 100% 87599/87599 [00:00<00:00, 442056.80 examples/s]
Generating validation split: 100% 10570/10570 [00:00<00:00, 338852.70 examples/s]
Design: 9 corrupted conditions + 1 matched clean condition(s); 1,000 total generations.
config.json: 100% 726/726 [00:00<00:00, 3.59MB/s]
tokenizer_config.json: 100% 9.73k/9.73k [00:00<00:00, 9.02MB/s]
vocab.json: 100% 2.78M/2.78M [00:00<00:00, 13.6MB/s]
merges.txt: 100% 1.67M/1.67M [00:00<00:00, 11.5MB/s]

tokenizer.json: downloading bytes:  19% 2.18M/11.4M [00:01<00:04, 2.15MB/s]
tokenizer.json: downloading bytes: 100% 3.40M/3.40M [00:01<00:00, 3.26MB/s,  330kB/s  ]
tokenizer.json: reconstructing file: 100% 11.4M/11.4M [00:01<00:00, 11.0MB/s, 1.11MB/s  ]
model.safetensors.index.json: 100% 32.8k/32.8k [00:00<00:00, 54.6MB/s]
Downloading bytes:           |  0.00B
Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 3 files:   0% 0/3 [00:00<?, ?it/s]
Reconstructing (incomplete total...):   0% 0.00/4.09G [00:00<?, ?B/s]
Reconstructing (incomplete total...):   0% 0.00/8.04G [00:00<?, ?B/s]
Downloading bytes:   2% 192M/8.04G [00:01<00:38, 204MB/s,  200MB/s  ]
Downloading bytes:   3% 249M/8.04G [00:01<00:28, 276MB/s,  204MB/s  ]
Reconstructing (incomplete total...):   1% 115M/8.04G [00:01<01:57, 67.4MB/s, 37.5MB/s  ]
Reconstructing (incomplete total...):   2% 165M/8.04G [00:02<01:14, 106MB/s, 67.4MB/s  ]

Downloading bytes:   4% 293M/8.04G [00:02<00:37, 208MB/s,  276MB/s  ]
Downloading bytes:   5% 392M/8.04G [00:02<00:31, 239MB/s,  214MB/s  ]
Downloading bytes:   7% 523M/8.04G [00:03<00:27, 272MB/s,  258MB/s  ]
Downloading bytes:   7% 558M/8.04G [00:03<00:32, 231MB/s,  272MB/s  ]
Downloading bytes:   8% 665M/8.04G [00:03<00:28, 260MB/s,  246MB/s  ]
Downloading bytes:  10% 777M/8.04G [00:04<00:26, 277MB/s,  268MB/s  ]
Downloading bytes:  15% 1.18G/8.04G [00:05<00:29, 235MB/s,  265MB/s  ]
Downloading bytes:  16% 1.32G/8.04G [00:06<00:33, 199MB/s,  200MB/s  ]
Downloading bytes:  26% 2.10G/8.04G [00:08<00:17, 340MB/s,  335MB/s  ]
Downloading bytes:  27% 2.20G/8.04G [00:09<00:35, 166MB/s,  176MB/s  ]
Downloading bytes:  28% 2.23G/8.04G [00:09<00:36, 158MB/s,  166MB/s  ]
Downloading bytes:  28% 2.26G/8.04G [00:10<00:37, 156MB/s,  158MB/s  ]
Downloading bytes:  31% 2.51G/8.04G [00:11<00:33, 167MB/s,  183MB/s  ]
Downloading bytes:  40% 3.20G/8.04G [00:14<00:25, 188MB/s,  203MB/s  ]
Downloading bytes:  41% 3.27G/8.04G [00:15<00:34, 139MB/s,  151MB/s  ]
Downloading bytes:  42% 3.39G/8.04G [00:16<00:39, 118MB/s,  115MB/s  ]
Downloading bytes:  46% 3.66G/8.04G [00:18<00:26, 166MB/s,  150MB/s  ]
Downloading bytes:  47% 3.77G/8.04G [00:18<00:24, 178MB/s,  181MB/s  ]
Downloading bytes:  48% 3.84G/8.04G [00:19<00:21, 198MB/s,  196MB/s  ]
Downloading bytes:  57% 4.55G/8.04G [00:21<00:15, 222MB/s,  306MB/s  ]
Downloading bytes:  68% 5.46G/8.04G [00:25<00:12, 202MB/s,  180MB/s  ]
Downloading bytes:  68% 5.51G/8.04G [00:25<00:23, 110MB/s, 95.6MB/s  ]
Downloading bytes:  70% 5.65G/8.04G [00:36<01:01, 38.9MB/s, 28.2MB/s  ]
Downloading bytes:  79% 6.35G/8.04G [00:40<00:08, 210MB/s,  204MB/s  ]
Downloading bytes:  79% 6.39G/8.04G [00:42<00:38, 42.7MB/s, 37.8MB/s  ]
Downloading bytes:  84% 6.75G/8.04G [00:45<00:08, 145MB/s,  129MB/s  ]
Downloading bytes:  87% 6.99G/8.04G [00:46<00:04, 260MB/s,  246MB/s  ]
Reconstructing (incomplete total...):  81% 6.48G/8.04G [00:49<00:10, 143MB/s,  156MB/s  ]
Reconstructing (incomplete total...):  84% 6.78G/8.04G [00:51<00:09, 140MB/s,  143MB/s  ]

Fetching 3 files:  67% 2/3 [00:51<00:30, 30.16s/it]
Downloading bytes:  87% 7.01G/8.04G [01:01<00:03, 260MB/s,  260MB/s  ]
Reconstructing (incomplete total...):  97% 7.84G/8.04G [01:07<00:02, 87.6MB/s, 98.1MB/s  ]
Reconstructing (incomplete total...): 100% 8.04G/8.04G [01:08<00:00, 97.3MB/s, 87.6MB/s  ]

Fetching 3 files: 100% 3/3 [01:08<00:00, 22.85s/it]
Download complete: 100% 7.01G/7.01G [01:08<00:00, 260MB/s,  260MB/s  ]
Reconstruction complete: 100% 8.04G/8.04G [01:08<00:00, 117MB/s, 97.3MB/s  ]
Download complete: 100% 7.01G/7.01G [01:08<00:00, 102MB/s,  260MB/s  ]
Loading weights: 100% 398/398 [00:26<00:00, 15.14it/s]
generation_config.json: 100% 239/239 [00:00<00:00, 935kB/s]
Running clean baseline | mitigation=none on 100 squad examples...
100% 100/100 [02:05<00:00,  1.26s/it]
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/3
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=2/3
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=3/3
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/3
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=2/3
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=3/3
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/3
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=2/3
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=3/3

=== PRIMARY SUMMARY ===
        model  task  severity typo_difficulty mitigation   n  requested_n  excluded_examples_due_to_errors  clean_score    score  absolute_drop  drop_ci_2.5  drop_ci_97.5  bootstrap_probability_drop_le_zero
Qwen/Qwen3-4B squad         3            hard       none 100          100                                0     0.881346 0.775053       0.106292     0.056795      0.159095                                 0.0

The full condition-level summary was written to disk; use it for secondary typo-type/location analyses.

Raw results: results/qwen_squad_severity3_replicated.csv
Summary:     results/qwen_squad_severity3_replicated_summary.csv
Primary:     results/qwen_squad_severity3_replicated_primary_summary.csv
Metadata:    results/qwen_squad_severity3_replicated_metadata.json

In [12]:
!python capstone_robustness.py \
  --task squad \
  --backend hf \
  --model meta-llama/Llama-3.2-3B-Instruct \
  --n_samples 100 \
  --seed 42 \
  --typo_types keyboard deletion transposition \
  --match_typo_targets \
  --locations any \
  --severities 3 \
  --typo_difficulty hard \
  --corruption_replicates 3 \
  --output results/llama_squad_severity3_replicated.csv

Design: 9 corrupted conditions + 1 matched clean condition(s); 1,000 total generations.
config.json: 100% 878/878 [00:00<00:00, 3.70MB/s]
tokenizer_config.json: 100% 54.5k/54.5k [00:00<00:00, 86.2MB/s]
tokenizer.json: 100% 9.09M/9.09M [00:01<00:00, 7.24MB/s]
special_tokens_map.json: 100% 296/296 [00:00<00:00, 1.24MB/s]
model.safetensors.index.json: 100% 20.9k/20.9k [00:00<00:00, 59.2MB/s]
Downloading bytes:           |  0.00B
Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0% 0/2 [00:00<?, ?it/s]
Reconstructing (incomplete total...):   0% 0.00/1.46G [00:00<?, ?B/s]
Downloading bytes:   3% 216M/6.43G [00:02<00:36, 169MB/s,  162MB/s  ]
Downloading bytes:   4% 236M/6.43G [00:02<00:43, 143MB/s,  169MB/s  ]
Downloading bytes:   6% 358M/6.43G [00:03<00:36, 166MB/s,  193MB/s  ]
Downloading bytes:   8% 507M/6.43G [00:04<00:28, 206MB/s,  200MB/s  ]
Downloading bytes:  11% 686M/6.43G [00:04<00:30, 191MB/s,  226MB/s  ]
Downloading bytes:  13% 829M/6.43G [00:05<00:32, 171MB/s,  187MB/s  ]
Downloading bytes:  14% 878M/6.43G [00:06<00:28, 196MB/s,  189MB/s  ]
Downloading bytes:  17% 1.09G/6.43G [00:06<00:20, 255MB/s,  267MB/s  ]
Downloading bytes:  20% 1.26G/6.43G [00:07<00:17, 293MB/s,  289MB/s  ]
Downloading bytes:  32% 2.03G/6.43G [00:09<00:14, 301MB/s,  325MB/s  ]
Downloading bytes:  35% 2.23G/6.43G [00:11<00:30, 139MB/s,  151MB/s  ]
Downloading bytes:  36% 2.29G/6.43G [00:11<00:25, 160MB/s,  157MB/s  ]
Downloading bytes:  38% 2.45G/6.43G [00:12<00:20, 198MB/s,  243MB/s  ]
Downloading bytes:  46% 2.96G/6.43G [00:14<00:17, 197MB/s,  205MB/s  ]
Downloading bytes:  56% 3.60G/6.43G [00:18<00:20, 137MB/s,  129MB/s  ]
Downloading bytes:  57% 3.66G/6.43G [00:19<00:18, 148MB/s,  143MB/s  ]
Downloading bytes:  60% 3.84G/6.43G [00:20<00:27, 94.4MB/s,  104MB/s  ]
Reconstructing (incomplete total...):  42% 2.68G/6.43G [00:20<00:28, 132MB/s,  138MB/s  ]

Downloading bytes:  62% 3.98G/6.43G [00:21<00:13, 177MB/s,  174MB/s  ]
Downloading bytes:  73% 4.70G/6.43G [00:24<00:05, 306MB/s,  304MB/s  ]
Downloading bytes:  77% 4.97G/6.43G [00:25<00:08, 164MB/s,  171MB/s  ]
Downloading bytes:  84% 5.43G/6.43G [00:28<00:04, 216MB/s,  216MB/s  ]
Downloading bytes:  86% 5.55G/6.43G [00:29<00:06, 138MB/s,  165MB/s  ]
Reconstructing (incomplete total...):  76% 4.86G/6.43G [00:30<00:06, 228MB/s,  204MB/s  ]
Reconstructing (incomplete total...):  84% 5.39G/6.43G [00:32<00:04, 236MB/s,  228MB/s  ]
Downloading bytes:  86% 5.55G/6.43G [00:41<00:06, 138MB/s,  138MB/s  ]
Reconstructing (incomplete total...): 100% 6.43G/6.43G [00:43<00:00, 134MB/s,  138MB/s  ]

Fetching 2 files: 100% 2/2 [00:43<00:00, 21.66s/it]
Download complete: 100% 5.55G/5.55G [00:43<00:00, 138MB/s,  138MB/s  ]
Reconstruction complete: 100% 6.43G/6.43G [00:43<00:00, 148MB/s,  134MB/s  ]
Download complete: 100% 5.55G/5.55G [00:43<00:00, 128MB/s,  138MB/s  ]
Loading weights: 100% 254/254 [00:19<00:00, 13.11it/s]
generation_config.json: 100% 189/189 [00:00<00:00, 820kB/s]
Running clean baseline | mitigation=none on 100 squad examples...
  0% 0/100 [00:00<?, ?it/s][transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
100% 100/100 [01:33<00:00,  1.07it/s]
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/3
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=2/3
Running keyboard | any | severity=3 | difficulty=hard | mitigation=none | replicate=3/3
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/3
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=2/3
Running deletion | any | severity=3 | difficulty=hard | mitigation=none | replicate=3/3
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=1/3
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=2/3
Running transposition | any | severity=3 | difficulty=hard | mitigation=none | replicate=3/3

=== PRIMARY SUMMARY ===
                           model  task  severity typo_difficulty mitigation   n  requested_n  excluded_examples_due_to_errors  clean_score    score  absolute_drop  drop_ci_2.5  drop_ci_97.5  bootstrap_probability_drop_le_zero
meta-llama/Llama-3.2-3B-Instruct squad         3            hard       none 100          100                                0     0.860356 0.693809       0.166547     0.117639      0.215435                                 0.0

The full condition-level summary was written to disk; use it for secondary typo-type/location analyses.

Raw results: results/llama_squad_severity3_replicated.csv
Summary:     results/llama_squad_severity3_replicated_summary.csv
Primary:     results/llama_squad_severity3_replicated_primary_summary.csv
Metadata:    results/llama_squad_severity3_replicated_metadata.json

In [13]:
!python compare_models.py \
  --inputs \
    results/qwen_squad_severity3_replicated.csv \
    results/llama_squad_severity3_replicated.csv \
  --mitigation none \
  --typo_difficulty hard \
  --output_dir results/cross_model_squad_severity3_replicated

Saved paired cross-model comparison to results/cross_model_squad_severity3_replicated. Positive model gaps mean model A degraded more than model B.